### ISSUE TITLE
[LICENSE] GPL is not compatible with restricting to non-commercial use

### ISSUE THREAD

**Issue by johnurbanik** [slideflow/slideflow#372]
## Description

Repository README [says](https://github.com/jamesdolezal/slideflow?tab=readme-ov-file#-license)

> This code is made available under the GPLv3 License and is available for non-commercial academic purposes.

but GPLv3 does not allow restricting usage.

## Expected behavior
Software using the GPLv3 [cannot restrict to non-commercial use](https://www.gnu.org/licenses/gpl-faq.html#NoMilitary), so the README should be changed or the license should be changed.

**Comment by jamesdolezal** [comment]
Thanks John - this is something that is being actively discussed internally and will be updated at the next feature release.

**Comment by johnurbanik** [comment]
Thanks for the prompt response! Is any information available as to which direction is more likely (change of license or change of language)? Not asking for a guarantee, but some guidance would be helpful.

**Comment by jamesdolezal** [comment]
We are anticipating, but cannot yet confirm, changing the language to reflect the GPL-3 license which permits commercial use. We should have this sorted out officially within the next few weeks.

**Comment by jamesdolezal** [comment]
As a quick update, Slideflow will be switching to an **Apache-2.0** license with our version 3.0.0 release. Because Slideflow includes some modules with code incompatible with this license, we'll be separating those components into separate `slideflow-gpl` and `slideflow-noncommercial` packages, which will seamlessly integrate with the base `slideflow` library via package entry points (acting as a plugin). This clean separation of permissions will allow users to utilize Slideflow in a commercial environment. Researchers wanting access to additional non-commercial tools (e.g. pretrained feature extractors) can simply install `slideflow-noncommercial` and these additional tools will become automatically available.

The feature breakdown will be:
- **`slideflow-gpl`**: 
  - RetCCL, CTransPath
  - CLAM_SB, CLAM_MB
- **`slideflow-noncommercial`**
  - Gigapath, PLIP, UNI, HistoSSL
  - StyleGAN2 & StyleGAN3
  - BISCUIT UQ algorithm

Slideflow 3.0 is feature complete and has entered testing. We'll have a more formal announcement with additional information at the time of release.

**Comment by jamesdolezal** [comment]
Slideflow 3.0 has been released under the Apache-2.0 license. If anyone has thoughts or feedback on our license approach, we'd love to hear from you - please drop a note in our Discussion (https://github.com/slideflow/slideflow/discussions/407)
