### ISSUE TITLE
SlideFlow Studio crushes when clicking on 'Slides' button in the Project section

### ISSUE THREAD

**Issue by frasca17** [slideflow/slideflow#413]
Hi again, I am facing another issue these days with SlideFlow Studio 3.0.0

As soon as I open SlideFlow Studio, and I load the project correctly, when I go to open the slides, it immediatly crushes giving me an error that I attach below.

This was not happening while I was using SlideFlow Studio 2.3.1

How can I solve this issue?

And I would like to thank you very much for all the updates of the new version :)
![Screenshot 2024-09-05 at 16 20 12](https://github.com/user-attachments/assets/25b5190a-75de-4788-b325-dc049d02ab88)
![Screenshot 2024-09-05 at 16 19 04](https://github.com/user-attachments/assets/4e6d5fd0-aeb9-4612-8061-989dc0ab0465)

**Comment by jamesdolezal** [comment]
Thanks for raising this bug - I apologize this got through. The icon for the search filter didn't make it into our prepackaged python wheel, causing this error for people running from the PyPI install instead of source.

I will upload a patch release to PyPI later today. In the meantime, you should be able to work around this issue by running from source.
