### ISSUE TITLE
switching slide backend in python

### ISSUE THREAD

**Issue by zhangguy** [slideflow/slideflow#416]
Hi,
Thanks for developing this powerful platform. 
Is there a way to change the slide backend in python after slideflow is imported? I understand we can change it before starting python by setting the environment variable, but when I try to use slideflow in jupyterlab on a linux server, which I do not have control of the environment variable, the slide backend defaults to libvips. I installed the package using the conda method from the yaml file. If I use it in bash, the backend defaults to cucim, but it defaults to libvips when I use it in notebooks. 
```
import slideflow as sf
sf.about()
│ Slideflow                        │                                                                               
│ Version: 3.0.1+5.gef1ccccd.dirty │                                                                               
│ Backend: torch                   │                                                                               
│ Slide Backend: libvips (unknown) │                                                                               
│ https://slideflow.dev            │                                                                               
```
Thanks!

**Comment by jamesdolezal** [comment]
So this is tricky - the requirement to have the backend set upon import is due to a limitation of cuCIM / Libvips, not Slideflow.

It's been some time since we tested this, but to the best of my memory, is main issue is that the Libvips library is not fork-safe. This means that once Libvips is imported, you can no longer use fork-based multiprocessing (the default multiprocessing strategy) as it will result in a segfault. The reverse is true for cuCIM and spawn-based multiprocessing. This means that if both libraries are imported, you can no longer use any form of multiprocessing, as multiprocessing will inevitably result in either a thread lock or segmentation fault.

The solution is to force the backend strategy to be defined at import and ensure the alternative library is not imported.

With that said, there *is* a workaround for your issue with jupyter notebooks. You can set the environmental variable in a cell before importing slideflow using the below syntax:

```python
%env SF_SLIDE_BACKEND=libvips
import slideflow as sf
```

**Comment by zhangguy** [comment]
> So this is tricky - the requirement to have the backend set upon import is due to a limitation of cuCIM / Libvips, not Slideflow.
> 
> It's been some time since we tested this, but to the best of my memory, is main issue is that the Libvips library is not fork-safe. This means that once Libvips is imported, you can no longer use fork-based multiprocessing (the default multiprocessing strategy) as it will result in a segfault. The reverse is true for cuCIM and spawn-based multiprocessing. This means that if both libraries are imported, you can no longer use any form of multiprocessing, as multiprocessing will inevitably result in either a thread lock or segmentation fault.
> 
> The solution is to force the backend strategy to be defined at import and ensure the alternative library is not imported.
> 
> With that said, there _is_ a workaround for your issue with jupyter notebooks. You can set the environmental variable in a cell before importing slideflow using the below syntax:
> 
> ```python
> %env SF_SLIDE_BACKEND=libvips
> import slideflow as sf
> ```

It worked. thank you!
